// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bitcoin "nft/internal/handler/bitcoin"
	eth "nft/internal/handler/eth"
	"nft/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/account/new",
				Handler: bitcoin.NewAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/balance",
				Handler: bitcoin.GetBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recharge/check",
				Handler: bitcoin.CheckArrivedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recharge/platform",
				Handler: bitcoin.RechargePlatformHandler(serverCtx),
			},
		},
		rest.WithPrefix("/bitcoin/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/erc20/check",
				Handler: eth.CheckERC20ArrivedHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/recharge/check",
				Handler: eth.CheckEthArrivedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/eth/v1"),
	)
}
